### ISSUE TITLE
toggle_editor.js errors

### ISSUE THREAD

**Issue by SoxFace** [shawnr/gesso#9]
Hi Shawn, 

This tool is a great idea and much needed in Canvas LMS. Is this repo up to date?

I've installed it, but toggle_editor.js is struggling with console errors.

Any advice would be greatly appreciated. i.e 

A. forget it, start again 
B. No it's good - fix the dependency issues and rock on

Cheers
Sonya

<img width="488" alt="screenshot 2018-06-13 23 23 44" src="https://user-images.githubusercontent.com/4454398/41391627-4c685ca2-6f61-11e8-8a66-466589a013ba.png">

**Comment by shawnr** [comment]
Hi @SoxFace -- Thanks for posting the issue. This project has been discontinued for several years now. Due to the way Canvas LMS implements their templates there was no way to make this 100% safe, so I never took it all the way towards formally releasing the extension. It lives here in my code archives, but it is not maintained (and I have no plans to maintain it). Feel free to fork it and do what you will with it! -- Shawn
